spring:
  datasource:
    #账号配置
    url: jdbc:mysql://sh-cdb-5wr4bn64.sql.tencentcdb.com:63285/mallcloud?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useUnicode=true&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: root
    password: ZeueGhtMder83tBO
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    redis:
      time-to-live: 54s
      key-prefix: 'defult:'
      cache-null-values: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.common.model
  global-config:
    db-config:
      id-type: auto

custom:
  cache-manager:
    customCaches:
      test:
        time-to-live: 120s
        key-prefix: "GOOD:NAME:"
      test2:
        time-to-live: 240s
        key-prefix: "GOOD1:NAME1:"

swagger:
  enabled: true
  title: 搜索中心
  description: 搜索中心接口文档
  version: 1.0
  base-package: com.changyi.demo1.controller
