spring:
  application:
    name: demo1
  redis:
    host: 127.0.0.1
    port: 6379
  cache:
    redis:
      time-to-live: 54s
      key-prefix: 'defult:'
      cache-null-values: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.1:8848
      config:
        server-addr: 192.168.56.1:8848
custom:
  cache-manager:
    customCaches:
      test:
        time-to-live: 120s
        key-prefix: "GOOD:NAME:"
      test2:
        time-to-live: 240s
        key-prefix: "GOOD1:NAME1:"
server:
  port: 8082


